// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Curry = require("rescript/lib/js/curry.js");
var Belt_MapString = require("rescript/lib/js/belt_MapString.js");
var Belt_SetString = require("rescript/lib/js/belt_SetString.js");

function MakeEntity(Data) {
  var make = function (s) {
    return s;
  };
  var toString = function (t) {
    return t;
  };
  var Id = {
    make: make,
    toString: toString
  };
  var add = Belt_SetString.add;
  var remove = Belt_SetString.remove;
  var toArray = Belt_SetString.toArray;
  var size = Belt_SetString.size;
  var IdSet = {
    empty: undefined,
    add: add,
    remove: remove,
    toArray: toArray,
    size: size
  };
  var make$1 = function (data) {
    var id = Curry._1(Data.id, data);
    return {
            id: id,
            data: data
          };
  };
  var get = Belt_MapString.get;
  var add$1 = function (t, entity) {
    return Belt_MapString.set(t, entity.id, entity);
  };
  var remove$1 = Belt_MapString.remove;
  var size$1 = Belt_MapString.size;
  var has = Belt_MapString.has;
  var $$Map = {
    empty: undefined,
    get: get,
    add: add$1,
    remove: remove$1,
    size: size$1,
    has: has
  };
  return {
          Id: Id,
          IdSet: IdSet,
          make: make$1,
          $$Map: $$Map
        };
}

exports.MakeEntity = MakeEntity;
/* No side effect */
